language: node_js
node_js:
  - 11.15.0

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves fpr cypress tests
      - libgconf-2-4

before_install:
  - echo do pre-install things here...

install:
  - node --version
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  - pwd
  - npm install

before_script:
  - echo do pre-scripts things here...

script:
  # - ls
  # - gulp test
  # - protractor protractor.conf.js
  # - gulp build

  - npm start & wait-on http://localhost:8000
  - npm run e2e-headless

after_script:
  - echo ran script
after_success:
  - npm run build
  # - git config credential.helper "store --file=.git/credentials"
  # - echo "https://${GH_TOKEN}:@github.com/ng-nj.org.git" > .git/credentials
  # - echo 'Success'
  # - ls
  # - git config --global user.email "mrdotjim@gmail.com"
  # - git config --global user.name "JimTheMan"
  # - bash ./deploy.sh
  - echo Nice!
matrix:
  fast_finish: true

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
